/*! \file
 * \author Lorenzo Miniero <lorenzo@meetecho.com>
 * \author Sergey Radionov <rsatom@gmail.com>
 * \copyright GNU General Public License v3
 */

#pragma once

/* Plugin information */
#define PTT_AUDIOBRIDGE_VERSION			12
#define PTT_AUDIOBRIDGE_VERSION_STRING	"0.0.12"
#define PTT_AUDIOBRIDGE_DESCRIPTION		""
#define PTT_AUDIOBRIDGE_NAME				"JANUS PTT AudioBridge plugin"
#define PTT_AUDIOBRIDGE_AUTHOR			"Meetecho s.r.l. && Sergey Radionov <rsatom@gmail.com>"
#define PTT_AUDIOBRIDGE_PACKAGE			"janus.plugin.ptt-audiobridge"


#define MIN_SEQUENTIAL						2
#define MAX_MISORDER						50

#define  PTT_NO_AUDIO_TIMEOUT				5 // seconds

/* Mixer settings */
#define DEFAULT_PREBUFFERING	6
#define MAX_PREBUFFERING		50


/* Opus settings */
#define OPUS_SAMPLES	960
#define BUFFER_SAMPLES	OPUS_SAMPLES * 12


/* Error codes */
#define PTT_AUDIOBRIDGE_ERROR_UNKNOWN_ERROR	499
#define PTT_AUDIOBRIDGE_ERROR_NO_MESSAGE		480
#define PTT_AUDIOBRIDGE_ERROR_INVALID_JSON	481
#define PTT_AUDIOBRIDGE_ERROR_INVALID_REQUEST	482
#define PTT_AUDIOBRIDGE_ERROR_MISSING_ELEMENT	483
#define PTT_AUDIOBRIDGE_ERROR_INVALID_ELEMENT	484
#define PTT_AUDIOBRIDGE_ERROR_NO_SUCH_ROOM	485
#define PTT_AUDIOBRIDGE_ERROR_ROOM_EXISTS		486
#define PTT_AUDIOBRIDGE_ERROR_NOT_JOINED		487
#define PTT_AUDIOBRIDGE_ERROR_LIBOPUS_ERROR	488
#define PTT_AUDIOBRIDGE_ERROR_UNAUTHORIZED	489
#define PTT_AUDIOBRIDGE_ERROR_ID_EXISTS		490
#define PTT_AUDIOBRIDGE_ERROR_ALREADY_JOINED	491
#define PTT_AUDIOBRIDGE_ERROR_NO_SUCH_USER	492
#define PTT_AUDIOBRIDGE_ERROR_INVALID_SDP		493
#define PTT_AUDIOBRIDGE_ERROR_NO_SUCH_GROUP	494
#define PTT_AUDIOBRIDGE_ERROR_ROOM_ALREADY_HAS_UNMUTED_USER	600
#define PTT_AUDIOBRIDGE_ERROR_ROOM_ALREADY_PLAYING_FILE	601
